package com.codecool.ElProyecteGrande.enums;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum Country {
    @JsonProperty("USA") USA("United States of America"),
    @JsonProperty("Afghanistan") AFGHANISTAN("Afghanistan"),
    @JsonProperty("Albania") ALBANIA("Albania"),
    @JsonProperty("Algeria") ALGERIA("Algeria"),
    @JsonProperty("Andorra") ANDORRA("Andorra"),
    @JsonProperty("Angola") ANGOLA("Angola"),
    @JsonProperty("Antigua & Deps") ANTIGUA_DEPS("Antigua & Deps"),
    @JsonProperty("Argentina") ARGENTINA("Argentina"),
    @JsonProperty("Armenia") ARMENIA("Armenia"),
    @JsonProperty("Australia") AUSTRALIA("Australia"),
    @JsonProperty("Austria") AUSTRIA("Austria"),
    @JsonProperty("Azerbaijan") AZERBAIJAN("Azerbaijan"),
    @JsonProperty("Bahamas") BAHAMAS("Bahamas"),
    @JsonProperty("Bahrain") BAHRAIN("Bahrain"),
    @JsonProperty("Bangladesh") BANGLADESH("Bangladesh"),
    @JsonProperty("Barbados") BARBADOS("Barbados"),
    @JsonProperty("Belarus") BELARUS("Belarus"),
    @JsonProperty("Belgium") BELGIUM("Belgium"),
    @JsonProperty("Belize") BELIZE("Belize"),
    @JsonProperty("Benin") BENIN("Benin"),
    @JsonProperty("Bhutan") BHUTAN("Bhutan"),
    @JsonProperty("Bolivia") BOLIVIA("Bolivia"),
    @JsonProperty("Bosnia Herzegovina") BOSNIA_HERZEGOVINA("Bosnia Herzegovina"),
    @JsonProperty("Botswana") BOTSWANA("Botswana"),
    @JsonProperty("Brazil") BRAZIL("Brazil"),
    @JsonProperty("Brunei") BRUNEI("Brunei"),
    @JsonProperty("Bulgaria") BULGARIA("Bulgaria"),
    @JsonProperty("Burkina") BURKINA("Burkina"),
    @JsonProperty("Burma") BURMA("Burma"),
    @JsonProperty("Burundi") BURUNDI("Burundi"),
    @JsonProperty("Cambodia") CAMBODIA("Cambodia"),
    @JsonProperty("Cameroon") CAMEROON("Cameroon"),
    @JsonProperty("Canada") CANADA("Canada"),
    @JsonProperty("Cape Verde") CAPE_VERDE("Cape Verde"),
    @JsonProperty("Central African Rep") CENTRAL_AFRICAN_REP("Central African Rep"),
    @JsonProperty("Chad") CHAD("Chad"),
    @JsonProperty("Chile") CHILE("Chile"),
    @JsonProperty("Republic of China") CHINA("Republic of China"),
    @JsonProperty("Colombia") COLOMBIA("Colombia"),
    @JsonProperty("Costa Rica") COSTA_RICA("Costa Rica"),
    @JsonProperty("Croatia") CROATIA("Croatia"),
    @JsonProperty("Cuba") CUBA("Cuba"),
    @JsonProperty("Cyprus") CYPRUS("Cyprus"),
    @JsonProperty("Czech Republic") CZECH_REPUBLIC("Czech Republic"),
    @JsonProperty("Denmark") DENMARK("Denmark"),
    @JsonProperty("Dominican Republic") DOMINICAN_REPUBLIC("Dominican Republic"),
    @JsonProperty("Ecuador") ECUADOR("Ecuador"),
    @JsonProperty("Egypt") EGYPT("Egypt"),
    @JsonProperty("El Salvador") EL_SALVADOR("El Salvador"),
    @JsonProperty("Estonia") ESTONIA("Estonia"),
    @JsonProperty("Ethiopia") ETHIOPIA("Ethiopia"),
    @JsonProperty("Fiji") FIJI("Fiji"),
    @JsonProperty("Finland") FINLAND("Finland"),
    @JsonProperty("France") FRANCE("France"),
    @JsonProperty("Georgia") GEORGIA("Georgia"),
    @JsonProperty("Germany") GERMANY("Germany"),
    @JsonProperty("Greece") GREECE("Greece"),
    @JsonProperty("Grenada") GRENADA("Grenada"),
    @JsonProperty("Guatemala") GUATEMALA("Guatemala"),
    @JsonProperty("Guinea") GUINEA("Guinea"),
    @JsonProperty("Haiti") HAITI("Haiti"),
    @JsonProperty("Honduras") HONDURAS("Honduras"),
    @JsonProperty("Hungary") HUNGARY("Hungary"),
    @JsonProperty("Iceland") ICELAND("Iceland"),
    @JsonProperty("India") INDIA("India"),
    @JsonProperty("Indonesia") INDONESIA("Indonesia"),
    @JsonProperty("Iran") IRAN("Iran"),
    @JsonProperty("Iraq") IRAQ("Iraq"),
    @JsonProperty("Republic of Ireland") REPUBLIC_OF_IRELAND("Republic of Ireland"),
    @JsonProperty("Israel") ISRAEL("Israel"),
    @JsonProperty("Italy") ITALY("Italy"),
    @JsonProperty("Ivory Coast") IVORY_COAST("Ivory Coast"),
    @JsonProperty("Jamaica") JAMAICA("Jamaica"),
    @JsonProperty("Japan") JAPAN("Japan"),
    @JsonProperty("Jordan") JORDAN("Jordan"),
    @JsonProperty("Kazakhstan") KAZAKHSTAN("Kazakhstan"),
    @JsonProperty("Kenya") KENYA("Kenya"),
    @JsonProperty("North Korea") NORTH_KOREA("North Korea"),
    @JsonProperty("South Korea") SOUTH_KOREA("South Korea"),
    @JsonProperty("Kosovo") KOSOVO("Kosovo"),
    @JsonProperty("Kuwait") KUWAIT("Kuwait"),
    @JsonProperty("Kyrgyzstan") KYRGYZSTAN("Kyrgyzstan"),
    @JsonProperty("Laos") LAOS("Laos"),
    @JsonProperty("Latvia") LATVIA("Latvia"),
    @JsonProperty("Lebanon") LEBANON("Lebanon"),
    @JsonProperty("Libya") LIBYA("Libya"),
    @JsonProperty("Liechtenstein") LIECHTENSTEIN("Liechtenstein"),
    @JsonProperty("Lithuania") LITHUANIA("Lithuania"),
    @JsonProperty("Luxembourg") LUXEMBOURG("Luxembourg"),
    @JsonProperty("Macedonia") MACEDONIA("Macedonia"),
    @JsonProperty("Madagascar") MADAGASCAR("Madagascar"),
    @JsonProperty("Malaysia") MALAYSIA("Malaysia"),
    @JsonProperty("Maldives") MALDIVES("Maldives"),
    @JsonProperty("Malta") MALTA("Malta"),
    @JsonProperty("Mauritania") MAURITANIA("Mauritania"),
    @JsonProperty("Mauritius") MAURITIUS("Mauritius"),
    @JsonProperty("Mexico") MEXICO("Mexico"),
    @JsonProperty("Moldova") MOLDOVA("Moldova"),
    @JsonProperty("Monaco") MONACO("Monaco"),
    @JsonProperty("Mongolia") MONGOLIA("Mongolia"),
    @JsonProperty("Montenegro") MONTENEGRO("Montenegro"),
    @JsonProperty("Morocco") MOROCCO("Morocco"),
    @JsonProperty("Nepal") NEPAL("Nepal"),
    @JsonProperty("Netherlands") NETHERLANDS("Netherlands"),
    @JsonProperty("New Zealand") NEW_ZEALAND("New Zealand"),
    @JsonProperty("Nicaragua") NICARAGUA("Nicaragua"),
    @JsonProperty("Niger") NIGER("Niger"),
    @JsonProperty("Nigeria") NIGERIA("Nigeria"),
    @JsonProperty("Norway") NORWAY("Norway"),
    @JsonProperty("Oman") OMAN("Oman"),
    @JsonProperty("Pakistan") PAKISTAN("Pakistan"),
    @JsonProperty("Panama") PANAMA("Panama"),
    @JsonProperty("Papua New Guinea") PAPUA_NEW_GUINEA("Papua New Guinea"),
    @JsonProperty("Paraguay") PARAGUAY("Paraguay"),
    @JsonProperty("Peru") PERU("Peru"),
    @JsonProperty("Philippines") PHILIPPINES("Philippines"),
    @JsonProperty("Poland") POLAND("Poland"),
    @JsonProperty("Portugal") PORTUGAL("Portugal"),
    @JsonProperty("Qatar") QATAR("Qatar"),
    @JsonProperty("Romania") ROMANIA("Romania"),
    @JsonProperty("Russian Federation") RUSSIAN_FEDERATION("Russian Federation"),
    @JsonProperty("San Marino") SAN_MARINO("San Marino"),
    @JsonProperty("Saudi Arabia") SAUDI_ARABIA("Saudi Arabia"),
    @JsonProperty("Senegal") SENEGAL("Senegal"),
    @JsonProperty("Serbia") SERBIA("Serbia"),
    @JsonProperty("Singapore") SINGAPORE("Singapore"),
    @JsonProperty("Slovakia") SLOVAKIA("Slovakia"),
    @JsonProperty("Slovenia") SLOVENIA("Slovenia"),
    @JsonProperty("Somalia") SOMALIA("Somalia"),
    @JsonProperty("South Africa") SOUTH_AFRICA("South Africa"),
    @JsonProperty("Spain") SPAIN("Spain"),
    @JsonProperty("Sri Lanka") SRI_LANKA("Sri Lanka"),
    @JsonProperty("Sudan") SUDAN("Sudan"),
    @JsonProperty("Sweden") SWEDEN("Sweden"),
    @JsonProperty("Switzerland") SWITZERLAND("Switzerland"),
    @JsonProperty("Syria") SYRIA("Syria"),
    @JsonProperty("Thailand") THAILAND("Thailand"),
    @JsonProperty("Trinidad & Tobago") TRINIDAD_TOBAGO("Trinidad & Tobago"),
    @JsonProperty("Tunisia") TUNISIA("Tunisia"),
    @JsonProperty("Turkey") TURKEY("Turkey"),
    @JsonProperty("Ukraine") UKRAINE("Ukraine"),
    @JsonProperty("United Arab Emirates") UNITED_ARAB_EMIRATES("United Arab Emirates"),
    @JsonProperty("United Kingdom") UNITED_KINGDOM("United Kingdom"),
    @JsonProperty("Uruguay") URUGUAY("Uruguay"),
    @JsonProperty("Vatican City") VATICAN_CITY("Vatican City"),
    @JsonProperty("Venezuela") VENEZUELA("Venezuela"),
    @JsonProperty("Vietnam") VIETNAM("Vietnam");

    private String country;

    Country(String country) {
        this.country = country;
    }

    public String getName() {
        return country;
    }

}
